### ISSUE TITLE
那现在windows是不是没法使用呢？我也是遇到了这个问题，也安装了这个pip install magent2，但是依然不行。

### ISSUE THREAD

**Issue by shswdmx1** [agi-brain/xuance#16]
您好，出现这个错误是因为当前版本没考虑到Windows系统下，magent2环境的动态链接库文件。您可以试着安装一下这个环境，再看是否还会出现该错误？
`pip install magent2`
我们后期会修补这个问题，感谢您的反馈!

_Originally posted by @wenzhangliu in https://github.com/agi-brain/xuance/issues/7#issuecomment-1737166370_

**Comment by wenzhangliu** [comment]
你好，这个问题我们已经修复好了，测试可行。请问你安装的是哪个xuance版本？

**Comment by shswdmx1** [comment]
Step 1: Create a new conda environment (python>=3.7 is suggested):

conda create -n xuance_env python=3.7
Step 2: Activate conda environment:

conda activate xuance_env
Step 3: Install the library:

pip install xuance
This command does not include the dependencies of deep learning toolboxes. To install the XuanCe with deep learning tools, you can type for [PyTorch](https://pytorch.org/get-started/locally/), for [TensorFlow2](https://www.tensorflow.org/install), for [MindSpore](https://www.mindspore.cn/install/en), and for all dependencies.pip install xuance[torch]pip install xuance[tensorflow]pip install xuance[mindspore]pip install xuance[all]

Note: Some extra packages should be installed manually for further usage.
我就按照这个步骤安装，然后最后pip install xuance[torch]安装了torch版本的。然后运行您examples文件中的代码，就报错OSError: [WinError 126] 找不到指定的模块。

**Comment by wenzhangliu** [comment]
好的。那方便说一下你运行的是哪个实例吗？另外最好能提供一下你安装的xuance版本，可以用pip list查看一下。最后还要麻烦截一个更完整的报错信息，便于帮助你找到报错的原因。

**Comment by shswdmx1** [comment]
运行的实例是examples中的dqn_atari.py；xuance版本是1.0.5；报错信息截图：
![GT C964XA%{E(H7_XGXK}R](https://github.com/agi-brain/xuance/assets/100499309/3ade7470-05c5-404e-bd5d-f5773615c43d)

**Comment by wenzhangliu** [comment]
这个是windows下的atari环境没有安装好的原因，和magent2没有关系了。可以先试试pip install gym[accept-rom-license]，不知道有没有用，期待反馈~

**Comment by shswdmx1** [comment]
感谢您的回复，但是似乎没什么用，而且我运行ppo_mujoco.py这个环境，也报这个错误。可能另有原因吧。

**Comment by wenzhangliu** [comment]
那应该和ale_c.dll这个动态链接库有关，你可以参考这个链接，试试看能不能解决你的问题？

[https://www.bilibili.com/read/cv17216467/](https://www.bilibili.com/read/cv17216467/)

**Comment by shswdmx1** [comment]
我参考这个链接https://blog.csdn.net/qq_27297393/article/details/105349229解决了这个问题
