### ISSUE TITLE
Is there any examples/tutorials for the magent2 environment?

### ISSUE THREAD

**Issue by shinyboy** [agi-brain/xuance#18]
Many thanks.

**Comment by wenzhangliu** [comment]
There is currently no instance for magent2 in examples. However, I can add relevant instances in the next few days. Please stay tuned for related Git commit information.

**Comment by shinyboy** [comment]
> There is currently no instance for magent2 in examples. However, I can add relevant instances in the next few days. Please stay tuned for related Git commit information.

Cool, many thanks.
Hope to see these examples soon.

**Comment by wenzhangliu** [comment]
Hi, my friend. I have added a preliminary example for magent2 environment. Hope that will help you in your research. I will also improve the code in the future plans.

**Comment by shinyboy** [comment]
Cool, thank you very much for such a quick response.
