### ISSUE TITLE
There is no 'SubprocVecEnv_MAgent', only 'DummyVecEnv_MAgent'? When will 'SubprocVecEnv_MAgent' be added?

### ISSUE THREAD

**Issue by shinyboy** [agi-brain/xuance#19]
Many thanks. I just found 'SubprocVecEnv_Pettingzoo', and there is no code referencing 'SubprocVecEnv_Pettingzoo'.

**Comment by wenzhangliu** [comment]
OK, I will add it right now! :)

**Comment by shinyboy** [comment]
Cool, many thanks for your quick reply.  :)
