### ISSUE TITLE
Parent directory does not exist

### ISSUE THREAD

**Issue by ycslnc** [agi-brain/xuance#20]
我运行了图上命令
![92 FL(4}ZUGTXSMHUESN)JG](https://github.com/agi-brain/xuance/assets/50171568/7dae6042-269a-46b8-ab48-1ba65105c52a)
然后遇到了这个报错，是需要修改配置文件中的保存路径吗
![UC3)YNR(H7P69L%_%%2~ RC](https://github.com/agi-brain/xuance/assets/50171568/d5853a64-f3ae-451b-9b59-5c960a9d05a1)

**Comment by wenzhangliu** [comment]
我怀疑可能是路径格式没有识别成功，刚刚修复了一下并上传了，麻烦您更新一下看看还存不存在这个问题。

**Comment by ycslnc** [comment]
还是会报错同样的错，log和models目录能创建，保存模型的时候会报错

**Comment by wenzhangliu** [comment]
不确定是不是因为目录里存在中文字符？
