### ISSUE TITLE
pygame.error: video system not initialized

### ISSUE THREAD

**Issue by ycslnc** [agi-brain/xuance#21]
运行demo_marl.py 训练正常，render报错
![image](https://github.com/agi-brain/xuance/assets/50171568/cb18fe09-f337-49d8-83a1-4cae6beb0b4a)

**Comment by wenzhangliu** [comment]
这个问题还是第一次遇到，查了一下网上也有不少相似的情况，可以参考这个链接看能不能解决：https://bobbyhadz.com/blog/pygame-error-video-system-not-initialized

**Comment by ycslnc** [comment]
只测试一次可以render，次数一多就会报错，感觉是环境close的时候有点问题。加了一行可以了，但是速度很快，根本看不清。。。render CartPole的时候还速度还挺正常
![image](https://github.com/agi-brain/xuance/assets/50171568/36f4de28-9533-4d07-8c48-9570a02c1515)

**Comment by wenzhangliu** [comment]
渲染速度你可以在env.render()函数里添加time.sleep(秒数)来控制。如果你是在tensorboard或者wandb里观察的话，可以改一下runner里的self.fps这个变量，我目前设置的是self.fps=20，这个变量表示frames per second. 后面我会把这个变量写进参数配置文件里，方便大家根据不同的设备来调。

**Comment by ycslnc** [comment]
好嘞，感谢~
