### ISSUE TITLE
大佬您好，是否有新增算法的教程或者模板

### ISSUE THREAD

**Issue by ShiXiangnan** [agi-brain/xuance#22]
R了个T~
想基于这个框架加自己的算法具体需要修改哪些内容呢？

**Comment by wenzhangliu** [comment]
我们近期正在做这方面的工作，标准的教程很快就会上线，敬请期待!

**Comment by ShiXiangnan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ShiXiangnan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
