### ISSUE TITLE
在pip install xuance[all]时遇到问题

### ISSUE THREAD

**Issue by Xqshyg** [agi-brain/xuance#29]
<img width="864" alt="联想截图_20240325160308" src="https://github.com/agi-brain/xuance/assets/157579337/6ffa4c40-14f5-414b-afbe-d4f44848995a">
如图，请问怎么解决啊？

**Comment by wenzhangliu** [comment]
请查看一下使用"pip install xuance[torch]"看有没有类似问题

**Comment by Xqshyg** [comment]
> 请查看一下使用"pip install xuance[torch]"看有没有类似问题

已解决，谢谢
