### ISSUE TITLE
MPE env not working.

### ISSUE THREAD

**Issue by chenhuiapp** [agi-brain/xuance#4]
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-8-0a9ac384711a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 runner = xp.get_runner(method='maddpg', 
      2                        env='mpe',
      3                        env_id='simple_spread',
      4                        is_test=False)

2 frames
[/usr/local/lib/python3.10/dist-packages/xuanpolicy/common/common_tools.py](https://localhost:8080/#) in get_config(file_name)
     22 
     23 def get_config(file_name):
---> 24     with open(file_name, "r") as f:
     25         try:
     26             config_dict = yaml.load(f, Loader=yaml.FullLoader)

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/xuanpolicy/configs/maddpg/mpe/simple_spread.yaml'

**Comment by wenzhangliu** [comment]
Hello, you need to use "simple_spread_v3" instead of "simple_spread" for env_id. You can also create a new file named "simple_spread.yaml" and set hyperparameters according to "xuanpolicy/configs/maddpg/mpe/simple_spread_v3.yaml". Then get runner by 
```python
runner = xp.get_runner(method='maddpg', env='mpe', 'env_id'='simple_spread_v3', 'config_path'='your config path', is_test=False)
````

**Comment by chenhuiapp** [comment]
Thank you.

How can I visualize a trained model, and how can i specify the action to be discrete or continuous?
