### ISSUE TITLE
examples\mappo\mappo_simple_spread.py running error

### ISSUE THREAD

**Issue by nessessary** [agi-brain/xuance#41]
git show
Date:   Sat Jun 8 23:49:32 2024 +0800
用pip install -e .安装后， 执行mappo_simple_spread.py报错如下
Traceback (most recent call last):
  File "I:\workc\MyWorkSource\wk\study\xuance\examples\mappo\mappo_simple_spread.py", line 289, in <module>
    runner = Runner(args)
  File "I:\workc\MyWorkSource\wk\study\xuance\examples\mappo\mappo_simple_spread.py", line 72, in __init__
    self.agent_keys = self.args.agent_keys = self.envs.agent_keys[0]
AttributeError: 'DummyVecMultiAgentEnv' object has no attribute 'agent_keys'
查看DummyVecMultiAgentEnv源码没有agent_keys相关, 本人小白， 想学习mappo， 希望作者帮忙解决一下。
用pip install xuance安装后跑文档里的快速开始例子没有问题
import xuance
runner = xuance.get_runner(method='mappo',
                           env='mpe',
                           env_id='simple_spread_v3',
                           is_test=True)
runner.run()
里面用的vectorize='Dummy_Pettingzoo'; 不知和DummyVecMultiAgentEnv有什么区别？

**Comment by wenzhangliu** [comment]
Hi, the version of xuance you have tried might be unstable, resulting in such errors. I suggest you to try the newest version of XuanCe (v1.2.1) to run MAPPO examples. Hope you all the best.
