### ISSUE TITLE
The actor networks cannot output negative values.

### ISSUE THREAD

**Issue by Aozaki-azk** [agi-brain/xuance#43]
你好，我在代码自定义环境中指定action_space范围为-1到1，但是网络输出的action只有0-1，请问是bug还是有其他地方需要配置
![QQ20240615-224537](https://github.com/agi-brain/xuance/assets/73455007/0e7a3aab-24b0-4aa0-b001-b92241dd5547)

**Comment by Aozaki-azk** [comment]
我当前使用的是maddpg，我用masac试了一下也不能输出负值

**Comment by wenzhangliu** [comment]
It is might because the activation function of the last layer in the actor-network is set as "sigmoid". In the newest version of XuanCe (v1.2.1), you can set the activation_action attribute to control the output range of actor networks.
