### ISSUE TITLE
OSError: exception: access violation reading 0x0000022A36EEA404

### ISSUE THREAD

**Issue by czf456789** [agi-brain/xuance#44]
![985acc9c73472f4a882b0e880cc6c45f](https://github.com/agi-brain/xuance/assets/58205433/41f7bc9f-2d2f-49a1-bb2f-43684827ac32)
@wenzhangliu 当我把magent2 adversarial_pursuit_v4环境改为battle_v4环境后 运行到第三轮会出现这个错误 请问该如何解决

**Comment by wenzhangliu** [comment]
您好，该错误是由于magent2官方环境还存在bug，目前我们决定暂时放弃对该环境的支持，直到官方给出可稳定运行的版本。给您造成不便我们深感抱歉。
