### ISSUE TITLE
ppo算法离散情况（policy采用Categorical_AC）多维离散动作的替代

### ISSUE THREAD

**Issue by HawkQ** [agi-brain/xuance#55]
目前ppo算法使用Categorical_AC时，如果action是二维，action_space采用MultiDiscrete定义，会回报
`AttributeError: 'MultiDiscrete' object has no attribute 'n'`
查看报错是因为需要通过action_space.n获取action_dim，但MultiDiscrete没有n故报错
我的动作空间是二维离散，请问有其他方式替代吗？
感谢！

**Comment by wenzhangliu** [comment]
非常抱歉，玄策暂时还不支持`MultiDiscrete`，可以考虑将二维离散动作编码为一维离散动作再作处理。
