### ISSUE TITLE
是否支持断点续训

### ISSUE THREAD

**Issue by mostcute** [agi-brain/xuance#59]
有没有支持从某个模型继续往下训练的功能，支持一个新环境的话很可能连续性不是很好，需要手动从上次模型继续训练新的模型

**Comment by mostcute** [comment]
我看到了learner的snapshot相关函数

是否可以给出一个简单的保存训练数据和模型（model & snapshot）再读取出来继续训练的example

**Comment by wenzhangliu** [comment]
很好的建议，我们会在example里增加这个功能的，感谢您的反馈。
