### ISSUE TITLE
COMA didn't work

### ISSUE THREAD

**Issue by TreeB-450** [agi-brain/xuance#6]
![image](https://github.com/agi-brain/xuanpolicy/assets/100345043/9c2f06ec-728c-4d90-8094-d6f833d8264e)
I don't know what's wrong, other algorithms could run as normal.

**Comment by wenzhangliu** [comment]
Currently, the COMA, VDAC, and MFAC need to be improved for some bugs. We are sorry for that and will solve the bugs very soon. Thank you for the question!

**Comment by wenzhangliu** [comment]
Hi, the COMA algorithm works now in the newest version of XuanPolicy. Please feel free to contact me if you have any questions.

**Comment by wenzhangliu** [comment]
The COMA algorithm in the newest version can work now.
