### ISSUE TITLE
使用robotic_warehouse环境问题

### ISSUE THREAD

**Issue by twy-oss** [agi-brain/xuance#62]
问题如下
<img width="551" alt="微信图片_20241106132553" src="https://github.com/user-attachments/assets/d06c4a80-2291-478e-8694-8acce0d8c195">
XuanCeMultiAgentEnvWrapper对象的agent_keys属性，这个对象没有这个属性。

**Comment by wenzhangliu** [comment]
你好，该问题是因为MAPPO新版本更新后，对应的环境没有及时更新的原因，我们将尽快更新相应的代码，非常抱歉。
