### ISSUE TITLE
Expected one type argument after "Optional" Pylance  reportInvalidTypeForm

### ISSUE THREAD

**Issue by SunSkyLH** [agi-brain/xuance#63]
xuance\torch\agents\core\off_policy_marl.py

OffPolicyMARLAgents类中__init__方法，self.memory: Optional[MARL_OffPolicyBuffer, MARL_OffPolicyBuffer_RNN] = None
这句代码的Optional使用了多个类型 MARL_OffPolicyBuffer, MARL_OffPolicyBuffer_RNN，提示报错

**Comment by wenzhangliu** [comment]
Could you please post the error message?

**Comment by SunSkyLH** [comment]
![xuance](https://github.com/user-attachments/assets/ce79ced4-8971-4660-9db7-20aec4caf366)

**Comment by wenzhangliu** [comment]
What happens if you ignore it and run the code? Will any errors be printed?
