### ISSUE TITLE
Directory not found when saving model

### ISSUE THREAD

**Issue by Peter-of-Astora** [agi-brain/xuance#64]
I'm running the quick-start code. And there's something wrong with the path of the model to be saved.

![屏幕截图 2024-11-29 111052](https://github.com/user-attachments/assets/d94f6d54-be53-4401-a7a1-1915b8ab3301)

I wonder the cause of this error. I think it might be the Windows system that generated the backslashes, causing the path to be incorrectly recognized. But I'm not sure. And I don't know how to fix this without altering the source code of the package.

**Comment by wenzhangliu** [comment]
Which version of XuanCe did you install?

**Comment by wenzhangliu** [comment]
I also guess the Python failed to recognize the folder name under E://???. You can rename the folder to an English name and retry.

**Comment by Peter-of-Astora** [comment]
I've changed the directory of the project and it works. Thank you!😊
