### ISSUE TITLE
OSError: [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by blog666** [agi-brain/xuance#7]
![image](https://github.com/agi-brain/xuanpolicy/assets/41368846/f70a455c-cda9-478f-a94a-c1df52198f8f)
会出现这个错误，不知道怎么解决，

**Comment by wenzhangliu** [comment]
您好，出现这个错误是因为当前版本没考虑到Windows系统下，magent2环境的动态链接库文件。您可以试着安装一下这个环境，再看是否还会出现该错误？
`pip install magent2`
我们后期会修补这个问题，感谢您的反馈!

**Comment by blog666** [comment]
还会出现该错误，已经环境转为linux，运行正常。谢谢解答
